name: let-it-snow
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=11.8
  - cuda-toolkit=11.8.0
  - pip
  - pip:
    - setuptools<70
    - plyfile
    - tqdm
    - scipy
    - numpy<2
    - imageio
    - imageio-ffmpeg
    - open3d
    - taichi
    - opencv-python
    - omegaconf
    - einops
    - diffusers==0.30.3
    - transformers==4.46.3
    - sentencepiece
    - accelerate
    - lpips
