name: let-it-snow
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=11.8
  - pip
  - pip:
    - plyfile
    - tqdm
    - scipy
    - numpy
    - imageio
    - imageio-ffmpeg
    - open3d
    - taichi
    - opencv-python
    - omegaconf
    - einops
    - diffusers
    - transformers
    - accelerate
